### ISSUE TITLE
Congratulations

### ISSUE THREAD

**Issue by rchastain** [Chessforeva/FreeBasicChess#1]
Hello!

It isn't really an "issue". I just want to congratulate you about your different chess projects. FreeBASIC, Lua, ActionScript... Great!

I am myself a hobbyist chess programmer. I made a chess program for FreeBASIC:
http://www.eschecs.fr/basic.html

and another for Lazarus:
http://www.eschecs.fr/pascal.html

I am also interested in Lua and Flash, but hadn't already made something interesting with these languages, except a simple EPD/FEN viewer (written in Flash Pascal):
http://www.eschecs.fr/epd-viewer.html

I would like to know a little more about you. From what country are you?
For me, I am French. :)

Best regards.

Roland

**Comment by Chessforeva** [comment]
Hi, my condolences.
I live in Latvia (domain .lv) - to the right - border of EU.
It's nice to see similar hobby things :)

Regards,
Chessforeva

2015-11-13 21:06 GMT+02:00 Roland Chastain notifications@github.com:

**Comment by rchastain** [comment]
Thank you.

I didn't know the name "Latvia". In french we say "Lettonie". :)

Yesterday I began to study your Lua version of Garbo Chess. You have done a great work! The Lua version of Fruit is also a great work. Maybe I will use them in a future project. Maybe also I will make a Pascal version of Fruit. For me Lua is easier to understand than C. :)

Good luck in your future projects!

Best regards.

Roland
